server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://10.6.8.98/login?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: hzdbserver
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        initialSize: 10
        minIdle: 10
        maxActive: 200
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: false

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.pan.example.testspringbootdemo.models  # 注意：对应实体类的路径
