package com.pan.example.testspringbootdemo.models;

import java.io.Serializable;

public class Tbareaconfigbackups implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbAreaConfigBackups.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbAreaConfigBackups.areaId
     *
     * @mbggenerated
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbAreaConfigBackups.oldAreaId
     *
     * @mbggenerated
     */
    private Integer oldAreaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbAreaConfigBackups.dbUrl
     *
     * @mbggenerated
     */
    private String dbUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbAreaConfigBackups.dbUser
     *
     * @mbggenerated
     */
    private String dbUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbAreaConfigBackups.dbPassword
     *
     * @mbggenerated
     */
    private String dbPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbAreaConfigBackups.info
     *
     * @mbggenerated
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbAreaConfigBackups
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbAreaConfigBackups.id
     *
     * @return the value of tbAreaConfigBackups.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbAreaConfigBackups.id
     *
     * @param id the value for tbAreaConfigBackups.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbAreaConfigBackups.areaId
     *
     * @return the value of tbAreaConfigBackups.areaId
     *
     * @mbggenerated
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbAreaConfigBackups.areaId
     *
     * @param areaId the value for tbAreaConfigBackups.areaId
     *
     * @mbggenerated
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbAreaConfigBackups.oldAreaId
     *
     * @return the value of tbAreaConfigBackups.oldAreaId
     *
     * @mbggenerated
     */
    public Integer getOldAreaId() {
        return oldAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbAreaConfigBackups.oldAreaId
     *
     * @param oldAreaId the value for tbAreaConfigBackups.oldAreaId
     *
     * @mbggenerated
     */
    public void setOldAreaId(Integer oldAreaId) {
        this.oldAreaId = oldAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbAreaConfigBackups.dbUrl
     *
     * @return the value of tbAreaConfigBackups.dbUrl
     *
     * @mbggenerated
     */
    public String getDbUrl() {
        return dbUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbAreaConfigBackups.dbUrl
     *
     * @param dbUrl the value for tbAreaConfigBackups.dbUrl
     *
     * @mbggenerated
     */
    public void setDbUrl(String dbUrl) {
        this.dbUrl = dbUrl == null ? null : dbUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbAreaConfigBackups.dbUser
     *
     * @return the value of tbAreaConfigBackups.dbUser
     *
     * @mbggenerated
     */
    public String getDbUser() {
        return dbUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbAreaConfigBackups.dbUser
     *
     * @param dbUser the value for tbAreaConfigBackups.dbUser
     *
     * @mbggenerated
     */
    public void setDbUser(String dbUser) {
        this.dbUser = dbUser == null ? null : dbUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbAreaConfigBackups.dbPassword
     *
     * @return the value of tbAreaConfigBackups.dbPassword
     *
     * @mbggenerated
     */
    public String getDbPassword() {
        return dbPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbAreaConfigBackups.dbPassword
     *
     * @param dbPassword the value for tbAreaConfigBackups.dbPassword
     *
     * @mbggenerated
     */
    public void setDbPassword(String dbPassword) {
        this.dbPassword = dbPassword == null ? null : dbPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbAreaConfigBackups.info
     *
     * @return the value of tbAreaConfigBackups.info
     *
     * @mbggenerated
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbAreaConfigBackups.info
     *
     * @param info the value for tbAreaConfigBackups.info
     *
     * @mbggenerated
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbAreaConfigBackups
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", areaId=").append(areaId);
        sb.append(", oldAreaId=").append(oldAreaId);
        sb.append(", dbUrl=").append(dbUrl);
        sb.append(", dbUser=").append(dbUser);
        sb.append(", dbPassword=").append(dbPassword);
        sb.append(", info=").append(info);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}