package com.pan.example.testspringbootdemo.models;

import java.io.Serializable;
import java.util.Date;

public class Tbbillorderbak implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.accountId
     *
     * @mbggenerated
     */
    private Long accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.accountName
     *
     * @mbggenerated
     */
    private String accountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.playerId
     *
     * @mbggenerated
     */
    private Long playerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.playerName
     *
     * @mbggenerated
     */
    private String playerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.status
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.createDate
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.modifyDate
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.areaId
     *
     * @mbggenerated
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.playerLevel
     *
     * @mbggenerated
     */
    private Short playerLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.money
     *
     * @mbggenerated
     */
    private Integer money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.chargeType
     *
     * @mbggenerated
     */
    private Integer chargeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.payType
     *
     * @mbggenerated
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.billDefineId
     *
     * @mbggenerated
     */
    private Integer billDefineId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.regChannelId
     *
     * @mbggenerated
     */
    private Integer regChannelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.regSubChannelId
     *
     * @mbggenerated
     */
    private Integer regSubChannelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.submitChannelId
     *
     * @mbggenerated
     */
    private Integer submitChannelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.submitSubChannelId
     *
     * @mbggenerated
     */
    private Integer submitSubChannelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.gainMoney1
     *
     * @mbggenerated
     */
    private Integer gainMoney1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.gainMoney2
     *
     * @mbggenerated
     */
    private Integer gainMoney2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.awardId1
     *
     * @mbggenerated
     */
    private Integer awardId1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.awardNum1
     *
     * @mbggenerated
     */
    private Short awardNum1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.awardId2
     *
     * @mbggenerated
     */
    private Integer awardId2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.awardNum2
     *
     * @mbggenerated
     */
    private Short awardNum2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.awardId3
     *
     * @mbggenerated
     */
    private Integer awardId3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.awardNum3
     *
     * @mbggenerated
     */
    private Short awardNum3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.serialNumber
     *
     * @mbggenerated
     */
    private String serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.clientInfoOpersys
     *
     * @mbggenerated
     */
    private Integer clientInfoOpersys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.clientInfoIp
     *
     * @mbggenerated
     */
    private String clientInfoIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.billId
     *
     * @mbggenerated
     */
    private Integer billId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.clientInfoSign
     *
     * @mbggenerated
     */
    private String clientInfoSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbBillOrderBak.clientInfoUid
     *
     * @mbggenerated
     */
    private String clientInfoUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbBillOrderBak
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.id
     *
     * @return the value of tbBillOrderBak.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.id
     *
     * @param id the value for tbBillOrderBak.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.accountId
     *
     * @return the value of tbBillOrderBak.accountId
     *
     * @mbggenerated
     */
    public Long getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.accountId
     *
     * @param accountId the value for tbBillOrderBak.accountId
     *
     * @mbggenerated
     */
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.accountName
     *
     * @return the value of tbBillOrderBak.accountName
     *
     * @mbggenerated
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.accountName
     *
     * @param accountName the value for tbBillOrderBak.accountName
     *
     * @mbggenerated
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.playerId
     *
     * @return the value of tbBillOrderBak.playerId
     *
     * @mbggenerated
     */
    public Long getPlayerId() {
        return playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.playerId
     *
     * @param playerId the value for tbBillOrderBak.playerId
     *
     * @mbggenerated
     */
    public void setPlayerId(Long playerId) {
        this.playerId = playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.playerName
     *
     * @return the value of tbBillOrderBak.playerName
     *
     * @mbggenerated
     */
    public String getPlayerName() {
        return playerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.playerName
     *
     * @param playerName the value for tbBillOrderBak.playerName
     *
     * @mbggenerated
     */
    public void setPlayerName(String playerName) {
        this.playerName = playerName == null ? null : playerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.status
     *
     * @return the value of tbBillOrderBak.status
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.status
     *
     * @param status the value for tbBillOrderBak.status
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.createDate
     *
     * @return the value of tbBillOrderBak.createDate
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.createDate
     *
     * @param createDate the value for tbBillOrderBak.createDate
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.modifyDate
     *
     * @return the value of tbBillOrderBak.modifyDate
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.modifyDate
     *
     * @param modifyDate the value for tbBillOrderBak.modifyDate
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.areaId
     *
     * @return the value of tbBillOrderBak.areaId
     *
     * @mbggenerated
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.areaId
     *
     * @param areaId the value for tbBillOrderBak.areaId
     *
     * @mbggenerated
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.playerLevel
     *
     * @return the value of tbBillOrderBak.playerLevel
     *
     * @mbggenerated
     */
    public Short getPlayerLevel() {
        return playerLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.playerLevel
     *
     * @param playerLevel the value for tbBillOrderBak.playerLevel
     *
     * @mbggenerated
     */
    public void setPlayerLevel(Short playerLevel) {
        this.playerLevel = playerLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.money
     *
     * @return the value of tbBillOrderBak.money
     *
     * @mbggenerated
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.money
     *
     * @param money the value for tbBillOrderBak.money
     *
     * @mbggenerated
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.chargeType
     *
     * @return the value of tbBillOrderBak.chargeType
     *
     * @mbggenerated
     */
    public Integer getChargeType() {
        return chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.chargeType
     *
     * @param chargeType the value for tbBillOrderBak.chargeType
     *
     * @mbggenerated
     */
    public void setChargeType(Integer chargeType) {
        this.chargeType = chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.payType
     *
     * @return the value of tbBillOrderBak.payType
     *
     * @mbggenerated
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.payType
     *
     * @param payType the value for tbBillOrderBak.payType
     *
     * @mbggenerated
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.billDefineId
     *
     * @return the value of tbBillOrderBak.billDefineId
     *
     * @mbggenerated
     */
    public Integer getBillDefineId() {
        return billDefineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.billDefineId
     *
     * @param billDefineId the value for tbBillOrderBak.billDefineId
     *
     * @mbggenerated
     */
    public void setBillDefineId(Integer billDefineId) {
        this.billDefineId = billDefineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.regChannelId
     *
     * @return the value of tbBillOrderBak.regChannelId
     *
     * @mbggenerated
     */
    public Integer getRegChannelId() {
        return regChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.regChannelId
     *
     * @param regChannelId the value for tbBillOrderBak.regChannelId
     *
     * @mbggenerated
     */
    public void setRegChannelId(Integer regChannelId) {
        this.regChannelId = regChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.regSubChannelId
     *
     * @return the value of tbBillOrderBak.regSubChannelId
     *
     * @mbggenerated
     */
    public Integer getRegSubChannelId() {
        return regSubChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.regSubChannelId
     *
     * @param regSubChannelId the value for tbBillOrderBak.regSubChannelId
     *
     * @mbggenerated
     */
    public void setRegSubChannelId(Integer regSubChannelId) {
        this.regSubChannelId = regSubChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.submitChannelId
     *
     * @return the value of tbBillOrderBak.submitChannelId
     *
     * @mbggenerated
     */
    public Integer getSubmitChannelId() {
        return submitChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.submitChannelId
     *
     * @param submitChannelId the value for tbBillOrderBak.submitChannelId
     *
     * @mbggenerated
     */
    public void setSubmitChannelId(Integer submitChannelId) {
        this.submitChannelId = submitChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.submitSubChannelId
     *
     * @return the value of tbBillOrderBak.submitSubChannelId
     *
     * @mbggenerated
     */
    public Integer getSubmitSubChannelId() {
        return submitSubChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.submitSubChannelId
     *
     * @param submitSubChannelId the value for tbBillOrderBak.submitSubChannelId
     *
     * @mbggenerated
     */
    public void setSubmitSubChannelId(Integer submitSubChannelId) {
        this.submitSubChannelId = submitSubChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.gainMoney1
     *
     * @return the value of tbBillOrderBak.gainMoney1
     *
     * @mbggenerated
     */
    public Integer getGainMoney1() {
        return gainMoney1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.gainMoney1
     *
     * @param gainMoney1 the value for tbBillOrderBak.gainMoney1
     *
     * @mbggenerated
     */
    public void setGainMoney1(Integer gainMoney1) {
        this.gainMoney1 = gainMoney1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.gainMoney2
     *
     * @return the value of tbBillOrderBak.gainMoney2
     *
     * @mbggenerated
     */
    public Integer getGainMoney2() {
        return gainMoney2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.gainMoney2
     *
     * @param gainMoney2 the value for tbBillOrderBak.gainMoney2
     *
     * @mbggenerated
     */
    public void setGainMoney2(Integer gainMoney2) {
        this.gainMoney2 = gainMoney2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.awardId1
     *
     * @return the value of tbBillOrderBak.awardId1
     *
     * @mbggenerated
     */
    public Integer getAwardId1() {
        return awardId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.awardId1
     *
     * @param awardId1 the value for tbBillOrderBak.awardId1
     *
     * @mbggenerated
     */
    public void setAwardId1(Integer awardId1) {
        this.awardId1 = awardId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.awardNum1
     *
     * @return the value of tbBillOrderBak.awardNum1
     *
     * @mbggenerated
     */
    public Short getAwardNum1() {
        return awardNum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.awardNum1
     *
     * @param awardNum1 the value for tbBillOrderBak.awardNum1
     *
     * @mbggenerated
     */
    public void setAwardNum1(Short awardNum1) {
        this.awardNum1 = awardNum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.awardId2
     *
     * @return the value of tbBillOrderBak.awardId2
     *
     * @mbggenerated
     */
    public Integer getAwardId2() {
        return awardId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.awardId2
     *
     * @param awardId2 the value for tbBillOrderBak.awardId2
     *
     * @mbggenerated
     */
    public void setAwardId2(Integer awardId2) {
        this.awardId2 = awardId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.awardNum2
     *
     * @return the value of tbBillOrderBak.awardNum2
     *
     * @mbggenerated
     */
    public Short getAwardNum2() {
        return awardNum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.awardNum2
     *
     * @param awardNum2 the value for tbBillOrderBak.awardNum2
     *
     * @mbggenerated
     */
    public void setAwardNum2(Short awardNum2) {
        this.awardNum2 = awardNum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.awardId3
     *
     * @return the value of tbBillOrderBak.awardId3
     *
     * @mbggenerated
     */
    public Integer getAwardId3() {
        return awardId3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.awardId3
     *
     * @param awardId3 the value for tbBillOrderBak.awardId3
     *
     * @mbggenerated
     */
    public void setAwardId3(Integer awardId3) {
        this.awardId3 = awardId3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.awardNum3
     *
     * @return the value of tbBillOrderBak.awardNum3
     *
     * @mbggenerated
     */
    public Short getAwardNum3() {
        return awardNum3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.awardNum3
     *
     * @param awardNum3 the value for tbBillOrderBak.awardNum3
     *
     * @mbggenerated
     */
    public void setAwardNum3(Short awardNum3) {
        this.awardNum3 = awardNum3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.serialNumber
     *
     * @return the value of tbBillOrderBak.serialNumber
     *
     * @mbggenerated
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.serialNumber
     *
     * @param serialNumber the value for tbBillOrderBak.serialNumber
     *
     * @mbggenerated
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber == null ? null : serialNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.remark
     *
     * @return the value of tbBillOrderBak.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.remark
     *
     * @param remark the value for tbBillOrderBak.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.clientInfoOpersys
     *
     * @return the value of tbBillOrderBak.clientInfoOpersys
     *
     * @mbggenerated
     */
    public Integer getClientInfoOpersys() {
        return clientInfoOpersys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.clientInfoOpersys
     *
     * @param clientInfoOpersys the value for tbBillOrderBak.clientInfoOpersys
     *
     * @mbggenerated
     */
    public void setClientInfoOpersys(Integer clientInfoOpersys) {
        this.clientInfoOpersys = clientInfoOpersys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.clientInfoIp
     *
     * @return the value of tbBillOrderBak.clientInfoIp
     *
     * @mbggenerated
     */
    public String getClientInfoIp() {
        return clientInfoIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.clientInfoIp
     *
     * @param clientInfoIp the value for tbBillOrderBak.clientInfoIp
     *
     * @mbggenerated
     */
    public void setClientInfoIp(String clientInfoIp) {
        this.clientInfoIp = clientInfoIp == null ? null : clientInfoIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.billId
     *
     * @return the value of tbBillOrderBak.billId
     *
     * @mbggenerated
     */
    public Integer getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.billId
     *
     * @param billId the value for tbBillOrderBak.billId
     *
     * @mbggenerated
     */
    public void setBillId(Integer billId) {
        this.billId = billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.clientInfoSign
     *
     * @return the value of tbBillOrderBak.clientInfoSign
     *
     * @mbggenerated
     */
    public String getClientInfoSign() {
        return clientInfoSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.clientInfoSign
     *
     * @param clientInfoSign the value for tbBillOrderBak.clientInfoSign
     *
     * @mbggenerated
     */
    public void setClientInfoSign(String clientInfoSign) {
        this.clientInfoSign = clientInfoSign == null ? null : clientInfoSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbBillOrderBak.clientInfoUid
     *
     * @return the value of tbBillOrderBak.clientInfoUid
     *
     * @mbggenerated
     */
    public String getClientInfoUid() {
        return clientInfoUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbBillOrderBak.clientInfoUid
     *
     * @param clientInfoUid the value for tbBillOrderBak.clientInfoUid
     *
     * @mbggenerated
     */
    public void setClientInfoUid(String clientInfoUid) {
        this.clientInfoUid = clientInfoUid == null ? null : clientInfoUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbBillOrderBak
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", accountId=").append(accountId);
        sb.append(", accountName=").append(accountName);
        sb.append(", playerId=").append(playerId);
        sb.append(", playerName=").append(playerName);
        sb.append(", status=").append(status);
        sb.append(", createDate=").append(createDate);
        sb.append(", modifyDate=").append(modifyDate);
        sb.append(", areaId=").append(areaId);
        sb.append(", playerLevel=").append(playerLevel);
        sb.append(", money=").append(money);
        sb.append(", chargeType=").append(chargeType);
        sb.append(", payType=").append(payType);
        sb.append(", billDefineId=").append(billDefineId);
        sb.append(", regChannelId=").append(regChannelId);
        sb.append(", regSubChannelId=").append(regSubChannelId);
        sb.append(", submitChannelId=").append(submitChannelId);
        sb.append(", submitSubChannelId=").append(submitSubChannelId);
        sb.append(", gainMoney1=").append(gainMoney1);
        sb.append(", gainMoney2=").append(gainMoney2);
        sb.append(", awardId1=").append(awardId1);
        sb.append(", awardNum1=").append(awardNum1);
        sb.append(", awardId2=").append(awardId2);
        sb.append(", awardNum2=").append(awardNum2);
        sb.append(", awardId3=").append(awardId3);
        sb.append(", awardNum3=").append(awardNum3);
        sb.append(", serialNumber=").append(serialNumber);
        sb.append(", remark=").append(remark);
        sb.append(", clientInfoOpersys=").append(clientInfoOpersys);
        sb.append(", clientInfoIp=").append(clientInfoIp);
        sb.append(", billId=").append(billId);
        sb.append(", clientInfoSign=").append(clientInfoSign);
        sb.append(", clientInfoUid=").append(clientInfoUid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}