package com.pan.example.testspringbootdemo.models;

import java.io.Serializable;

public class Tbfightcheckserverconfig implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbFightCheckServerConfig.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbFightCheckServerConfig.localIp
     *
     * @mbggenerated
     */
    private String localIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbFightCheckServerConfig.fightRmiPort
     *
     * @mbggenerated
     */
    private Integer fightRmiPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbFightCheckServerConfig.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbFightCheckServerConfig
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbFightCheckServerConfig.id
     *
     * @return the value of tbFightCheckServerConfig.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbFightCheckServerConfig.id
     *
     * @param id the value for tbFightCheckServerConfig.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbFightCheckServerConfig.localIp
     *
     * @return the value of tbFightCheckServerConfig.localIp
     *
     * @mbggenerated
     */
    public String getLocalIp() {
        return localIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbFightCheckServerConfig.localIp
     *
     * @param localIp the value for tbFightCheckServerConfig.localIp
     *
     * @mbggenerated
     */
    public void setLocalIp(String localIp) {
        this.localIp = localIp == null ? null : localIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbFightCheckServerConfig.fightRmiPort
     *
     * @return the value of tbFightCheckServerConfig.fightRmiPort
     *
     * @mbggenerated
     */
    public Integer getFightRmiPort() {
        return fightRmiPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbFightCheckServerConfig.fightRmiPort
     *
     * @param fightRmiPort the value for tbFightCheckServerConfig.fightRmiPort
     *
     * @mbggenerated
     */
    public void setFightRmiPort(Integer fightRmiPort) {
        this.fightRmiPort = fightRmiPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbFightCheckServerConfig.status
     *
     * @return the value of tbFightCheckServerConfig.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbFightCheckServerConfig.status
     *
     * @param status the value for tbFightCheckServerConfig.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbFightCheckServerConfig
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", localIp=").append(localIp);
        sb.append(", fightRmiPort=").append(fightRmiPort);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}