package com.pan.example.testspringbootdemo.models;

import java.io.Serializable;
import java.util.Date;

public class Tbgameloginaccountinfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameLoginAccountInfo.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameLoginAccountInfo.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameLoginAccountInfo.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameLoginAccountInfo.deviceId
     *
     * @mbggenerated
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameLoginAccountInfo.createTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameLoginAccountInfo.areaId
     *
     * @mbggenerated
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameLoginAccountInfo.gmUser
     *
     * @mbggenerated
     */
    private String gmUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameLoginAccountInfo.creatUser
     *
     * @mbggenerated
     */
    private String creatUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbGameLoginAccountInfo
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameLoginAccountInfo.id
     *
     * @return the value of tbGameLoginAccountInfo.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameLoginAccountInfo.id
     *
     * @param id the value for tbGameLoginAccountInfo.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameLoginAccountInfo.type
     *
     * @return the value of tbGameLoginAccountInfo.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameLoginAccountInfo.type
     *
     * @param type the value for tbGameLoginAccountInfo.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameLoginAccountInfo.ip
     *
     * @return the value of tbGameLoginAccountInfo.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameLoginAccountInfo.ip
     *
     * @param ip the value for tbGameLoginAccountInfo.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameLoginAccountInfo.deviceId
     *
     * @return the value of tbGameLoginAccountInfo.deviceId
     *
     * @mbggenerated
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameLoginAccountInfo.deviceId
     *
     * @param deviceId the value for tbGameLoginAccountInfo.deviceId
     *
     * @mbggenerated
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameLoginAccountInfo.createTime
     *
     * @return the value of tbGameLoginAccountInfo.createTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameLoginAccountInfo.createTime
     *
     * @param createTime the value for tbGameLoginAccountInfo.createTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameLoginAccountInfo.areaId
     *
     * @return the value of tbGameLoginAccountInfo.areaId
     *
     * @mbggenerated
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameLoginAccountInfo.areaId
     *
     * @param areaId the value for tbGameLoginAccountInfo.areaId
     *
     * @mbggenerated
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameLoginAccountInfo.gmUser
     *
     * @return the value of tbGameLoginAccountInfo.gmUser
     *
     * @mbggenerated
     */
    public String getGmUser() {
        return gmUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameLoginAccountInfo.gmUser
     *
     * @param gmUser the value for tbGameLoginAccountInfo.gmUser
     *
     * @mbggenerated
     */
    public void setGmUser(String gmUser) {
        this.gmUser = gmUser == null ? null : gmUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameLoginAccountInfo.creatUser
     *
     * @return the value of tbGameLoginAccountInfo.creatUser
     *
     * @mbggenerated
     */
    public String getCreatUser() {
        return creatUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameLoginAccountInfo.creatUser
     *
     * @param creatUser the value for tbGameLoginAccountInfo.creatUser
     *
     * @mbggenerated
     */
    public void setCreatUser(String creatUser) {
        this.creatUser = creatUser == null ? null : creatUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameLoginAccountInfo
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", type=").append(type);
        sb.append(", ip=").append(ip);
        sb.append(", deviceId=").append(deviceId);
        sb.append(", createTime=").append(createTime);
        sb.append(", areaId=").append(areaId);
        sb.append(", gmUser=").append(gmUser);
        sb.append(", creatUser=").append(creatUser);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}