package com.pan.example.testspringbootdemo.models;

import java.io.Serializable;
import java.util.Date;

public class Tbgamenotice implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameNotice.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameNotice.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameNotice.language
     *
     * @mbggenerated
     */
    private Integer language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameNotice.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameNotice.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameNotice.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameNotice.createTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameNotice.modifyTime
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameNotice.startTime
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameNotice.endTime
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameNotice.areaId
     *
     * @mbggenerated
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameNotice.channel
     *
     * @mbggenerated
     */
    private Integer channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameNotice.levelMin
     *
     * @mbggenerated
     */
    private Integer levelMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameNotice.levelMax
     *
     * @mbggenerated
     */
    private Integer levelMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameNotice.attr1
     *
     * @mbggenerated
     */
    private Integer attr1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameNotice.attr2
     *
     * @mbggenerated
     */
    private Integer attr2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameNotice.attr3
     *
     * @mbggenerated
     */
    private Integer attr3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameNotice.strs
     *
     * @mbggenerated
     */
    private String strs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameNotice.vipMin
     *
     * @mbggenerated
     */
    private Integer vipMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameNotice.vipMax
     *
     * @mbggenerated
     */
    private Integer vipMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameNotice.intervalTime
     *
     * @mbggenerated
     */
    private Integer intervalTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameNotice.location
     *
     * @mbggenerated
     */
    private Integer location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameNotice.imgId
     *
     * @mbggenerated
     */
    private String imgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameNotice.authUser
     *
     * @mbggenerated
     */
    private String authUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGameNotice.info
     *
     * @mbggenerated
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbGameNotice
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameNotice.id
     *
     * @return the value of tbGameNotice.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameNotice.id
     *
     * @param id the value for tbGameNotice.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameNotice.type
     *
     * @return the value of tbGameNotice.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameNotice.type
     *
     * @param type the value for tbGameNotice.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameNotice.language
     *
     * @return the value of tbGameNotice.language
     *
     * @mbggenerated
     */
    public Integer getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameNotice.language
     *
     * @param language the value for tbGameNotice.language
     *
     * @mbggenerated
     */
    public void setLanguage(Integer language) {
        this.language = language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameNotice.status
     *
     * @return the value of tbGameNotice.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameNotice.status
     *
     * @param status the value for tbGameNotice.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameNotice.title
     *
     * @return the value of tbGameNotice.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameNotice.title
     *
     * @param title the value for tbGameNotice.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameNotice.url
     *
     * @return the value of tbGameNotice.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameNotice.url
     *
     * @param url the value for tbGameNotice.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameNotice.createTime
     *
     * @return the value of tbGameNotice.createTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameNotice.createTime
     *
     * @param createTime the value for tbGameNotice.createTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameNotice.modifyTime
     *
     * @return the value of tbGameNotice.modifyTime
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameNotice.modifyTime
     *
     * @param modifyTime the value for tbGameNotice.modifyTime
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameNotice.startTime
     *
     * @return the value of tbGameNotice.startTime
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameNotice.startTime
     *
     * @param startTime the value for tbGameNotice.startTime
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameNotice.endTime
     *
     * @return the value of tbGameNotice.endTime
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameNotice.endTime
     *
     * @param endTime the value for tbGameNotice.endTime
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameNotice.areaId
     *
     * @return the value of tbGameNotice.areaId
     *
     * @mbggenerated
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameNotice.areaId
     *
     * @param areaId the value for tbGameNotice.areaId
     *
     * @mbggenerated
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameNotice.channel
     *
     * @return the value of tbGameNotice.channel
     *
     * @mbggenerated
     */
    public Integer getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameNotice.channel
     *
     * @param channel the value for tbGameNotice.channel
     *
     * @mbggenerated
     */
    public void setChannel(Integer channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameNotice.levelMin
     *
     * @return the value of tbGameNotice.levelMin
     *
     * @mbggenerated
     */
    public Integer getLevelMin() {
        return levelMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameNotice.levelMin
     *
     * @param levelMin the value for tbGameNotice.levelMin
     *
     * @mbggenerated
     */
    public void setLevelMin(Integer levelMin) {
        this.levelMin = levelMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameNotice.levelMax
     *
     * @return the value of tbGameNotice.levelMax
     *
     * @mbggenerated
     */
    public Integer getLevelMax() {
        return levelMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameNotice.levelMax
     *
     * @param levelMax the value for tbGameNotice.levelMax
     *
     * @mbggenerated
     */
    public void setLevelMax(Integer levelMax) {
        this.levelMax = levelMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameNotice.attr1
     *
     * @return the value of tbGameNotice.attr1
     *
     * @mbggenerated
     */
    public Integer getAttr1() {
        return attr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameNotice.attr1
     *
     * @param attr1 the value for tbGameNotice.attr1
     *
     * @mbggenerated
     */
    public void setAttr1(Integer attr1) {
        this.attr1 = attr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameNotice.attr2
     *
     * @return the value of tbGameNotice.attr2
     *
     * @mbggenerated
     */
    public Integer getAttr2() {
        return attr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameNotice.attr2
     *
     * @param attr2 the value for tbGameNotice.attr2
     *
     * @mbggenerated
     */
    public void setAttr2(Integer attr2) {
        this.attr2 = attr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameNotice.attr3
     *
     * @return the value of tbGameNotice.attr3
     *
     * @mbggenerated
     */
    public Integer getAttr3() {
        return attr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameNotice.attr3
     *
     * @param attr3 the value for tbGameNotice.attr3
     *
     * @mbggenerated
     */
    public void setAttr3(Integer attr3) {
        this.attr3 = attr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameNotice.strs
     *
     * @return the value of tbGameNotice.strs
     *
     * @mbggenerated
     */
    public String getStrs() {
        return strs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameNotice.strs
     *
     * @param strs the value for tbGameNotice.strs
     *
     * @mbggenerated
     */
    public void setStrs(String strs) {
        this.strs = strs == null ? null : strs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameNotice.vipMin
     *
     * @return the value of tbGameNotice.vipMin
     *
     * @mbggenerated
     */
    public Integer getVipMin() {
        return vipMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameNotice.vipMin
     *
     * @param vipMin the value for tbGameNotice.vipMin
     *
     * @mbggenerated
     */
    public void setVipMin(Integer vipMin) {
        this.vipMin = vipMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameNotice.vipMax
     *
     * @return the value of tbGameNotice.vipMax
     *
     * @mbggenerated
     */
    public Integer getVipMax() {
        return vipMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameNotice.vipMax
     *
     * @param vipMax the value for tbGameNotice.vipMax
     *
     * @mbggenerated
     */
    public void setVipMax(Integer vipMax) {
        this.vipMax = vipMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameNotice.intervalTime
     *
     * @return the value of tbGameNotice.intervalTime
     *
     * @mbggenerated
     */
    public Integer getIntervalTime() {
        return intervalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameNotice.intervalTime
     *
     * @param intervalTime the value for tbGameNotice.intervalTime
     *
     * @mbggenerated
     */
    public void setIntervalTime(Integer intervalTime) {
        this.intervalTime = intervalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameNotice.location
     *
     * @return the value of tbGameNotice.location
     *
     * @mbggenerated
     */
    public Integer getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameNotice.location
     *
     * @param location the value for tbGameNotice.location
     *
     * @mbggenerated
     */
    public void setLocation(Integer location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameNotice.imgId
     *
     * @return the value of tbGameNotice.imgId
     *
     * @mbggenerated
     */
    public String getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameNotice.imgId
     *
     * @param imgId the value for tbGameNotice.imgId
     *
     * @mbggenerated
     */
    public void setImgId(String imgId) {
        this.imgId = imgId == null ? null : imgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameNotice.authUser
     *
     * @return the value of tbGameNotice.authUser
     *
     * @mbggenerated
     */
    public String getAuthUser() {
        return authUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameNotice.authUser
     *
     * @param authUser the value for tbGameNotice.authUser
     *
     * @mbggenerated
     */
    public void setAuthUser(String authUser) {
        this.authUser = authUser == null ? null : authUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGameNotice.info
     *
     * @return the value of tbGameNotice.info
     *
     * @mbggenerated
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGameNotice.info
     *
     * @param info the value for tbGameNotice.info
     *
     * @mbggenerated
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameNotice
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", type=").append(type);
        sb.append(", language=").append(language);
        sb.append(", status=").append(status);
        sb.append(", title=").append(title);
        sb.append(", url=").append(url);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", areaId=").append(areaId);
        sb.append(", channel=").append(channel);
        sb.append(", levelMin=").append(levelMin);
        sb.append(", levelMax=").append(levelMax);
        sb.append(", attr1=").append(attr1);
        sb.append(", attr2=").append(attr2);
        sb.append(", attr3=").append(attr3);
        sb.append(", strs=").append(strs);
        sb.append(", vipMin=").append(vipMin);
        sb.append(", vipMax=").append(vipMax);
        sb.append(", intervalTime=").append(intervalTime);
        sb.append(", location=").append(location);
        sb.append(", imgId=").append(imgId);
        sb.append(", authUser=").append(authUser);
        sb.append(", info=").append(info);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}