package com.pan.example.testspringbootdemo.models;

import java.io.Serializable;
import java.util.Date;

public class Tbgiftorderbak implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGiftOrderBak.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGiftOrderBak.accountId
     *
     * @mbggenerated
     */
    private Long accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGiftOrderBak.accountName
     *
     * @mbggenerated
     */
    private String accountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGiftOrderBak.playerId
     *
     * @mbggenerated
     */
    private Long playerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGiftOrderBak.playerName
     *
     * @mbggenerated
     */
    private String playerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGiftOrderBak.status
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGiftOrderBak.createDate
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGiftOrderBak.modifyDate
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGiftOrderBak.areaId
     *
     * @mbggenerated
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGiftOrderBak.playerLevel
     *
     * @mbggenerated
     */
    private Short playerLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGiftOrderBak.money
     *
     * @mbggenerated
     */
    private Integer money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGiftOrderBak.chargeType
     *
     * @mbggenerated
     */
    private Integer chargeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGiftOrderBak.payType
     *
     * @mbggenerated
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGiftOrderBak.billDefineId
     *
     * @mbggenerated
     */
    private Integer billDefineId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGiftOrderBak.regChannelId
     *
     * @mbggenerated
     */
    private Integer regChannelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGiftOrderBak.regSubChannelId
     *
     * @mbggenerated
     */
    private Integer regSubChannelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGiftOrderBak.submitChannelId
     *
     * @mbggenerated
     */
    private Integer submitChannelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGiftOrderBak.submitSubChannelId
     *
     * @mbggenerated
     */
    private Integer submitSubChannelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGiftOrderBak.awardStr
     *
     * @mbggenerated
     */
    private String awardStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGiftOrderBak.serialNumber
     *
     * @mbggenerated
     */
    private String serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGiftOrderBak.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGiftOrderBak.clientInfoOpersys
     *
     * @mbggenerated
     */
    private Integer clientInfoOpersys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGiftOrderBak.clientInfoIp
     *
     * @mbggenerated
     */
    private String clientInfoIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGiftOrderBak.billId
     *
     * @mbggenerated
     */
    private Integer billId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGiftOrderBak.clientInfoSign
     *
     * @mbggenerated
     */
    private String clientInfoSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGiftOrderBak.clientInfoUid
     *
     * @mbggenerated
     */
    private String clientInfoUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbGiftOrderBak
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGiftOrderBak.id
     *
     * @return the value of tbGiftOrderBak.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGiftOrderBak.id
     *
     * @param id the value for tbGiftOrderBak.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGiftOrderBak.accountId
     *
     * @return the value of tbGiftOrderBak.accountId
     *
     * @mbggenerated
     */
    public Long getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGiftOrderBak.accountId
     *
     * @param accountId the value for tbGiftOrderBak.accountId
     *
     * @mbggenerated
     */
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGiftOrderBak.accountName
     *
     * @return the value of tbGiftOrderBak.accountName
     *
     * @mbggenerated
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGiftOrderBak.accountName
     *
     * @param accountName the value for tbGiftOrderBak.accountName
     *
     * @mbggenerated
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGiftOrderBak.playerId
     *
     * @return the value of tbGiftOrderBak.playerId
     *
     * @mbggenerated
     */
    public Long getPlayerId() {
        return playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGiftOrderBak.playerId
     *
     * @param playerId the value for tbGiftOrderBak.playerId
     *
     * @mbggenerated
     */
    public void setPlayerId(Long playerId) {
        this.playerId = playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGiftOrderBak.playerName
     *
     * @return the value of tbGiftOrderBak.playerName
     *
     * @mbggenerated
     */
    public String getPlayerName() {
        return playerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGiftOrderBak.playerName
     *
     * @param playerName the value for tbGiftOrderBak.playerName
     *
     * @mbggenerated
     */
    public void setPlayerName(String playerName) {
        this.playerName = playerName == null ? null : playerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGiftOrderBak.status
     *
     * @return the value of tbGiftOrderBak.status
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGiftOrderBak.status
     *
     * @param status the value for tbGiftOrderBak.status
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGiftOrderBak.createDate
     *
     * @return the value of tbGiftOrderBak.createDate
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGiftOrderBak.createDate
     *
     * @param createDate the value for tbGiftOrderBak.createDate
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGiftOrderBak.modifyDate
     *
     * @return the value of tbGiftOrderBak.modifyDate
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGiftOrderBak.modifyDate
     *
     * @param modifyDate the value for tbGiftOrderBak.modifyDate
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGiftOrderBak.areaId
     *
     * @return the value of tbGiftOrderBak.areaId
     *
     * @mbggenerated
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGiftOrderBak.areaId
     *
     * @param areaId the value for tbGiftOrderBak.areaId
     *
     * @mbggenerated
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGiftOrderBak.playerLevel
     *
     * @return the value of tbGiftOrderBak.playerLevel
     *
     * @mbggenerated
     */
    public Short getPlayerLevel() {
        return playerLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGiftOrderBak.playerLevel
     *
     * @param playerLevel the value for tbGiftOrderBak.playerLevel
     *
     * @mbggenerated
     */
    public void setPlayerLevel(Short playerLevel) {
        this.playerLevel = playerLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGiftOrderBak.money
     *
     * @return the value of tbGiftOrderBak.money
     *
     * @mbggenerated
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGiftOrderBak.money
     *
     * @param money the value for tbGiftOrderBak.money
     *
     * @mbggenerated
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGiftOrderBak.chargeType
     *
     * @return the value of tbGiftOrderBak.chargeType
     *
     * @mbggenerated
     */
    public Integer getChargeType() {
        return chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGiftOrderBak.chargeType
     *
     * @param chargeType the value for tbGiftOrderBak.chargeType
     *
     * @mbggenerated
     */
    public void setChargeType(Integer chargeType) {
        this.chargeType = chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGiftOrderBak.payType
     *
     * @return the value of tbGiftOrderBak.payType
     *
     * @mbggenerated
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGiftOrderBak.payType
     *
     * @param payType the value for tbGiftOrderBak.payType
     *
     * @mbggenerated
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGiftOrderBak.billDefineId
     *
     * @return the value of tbGiftOrderBak.billDefineId
     *
     * @mbggenerated
     */
    public Integer getBillDefineId() {
        return billDefineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGiftOrderBak.billDefineId
     *
     * @param billDefineId the value for tbGiftOrderBak.billDefineId
     *
     * @mbggenerated
     */
    public void setBillDefineId(Integer billDefineId) {
        this.billDefineId = billDefineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGiftOrderBak.regChannelId
     *
     * @return the value of tbGiftOrderBak.regChannelId
     *
     * @mbggenerated
     */
    public Integer getRegChannelId() {
        return regChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGiftOrderBak.regChannelId
     *
     * @param regChannelId the value for tbGiftOrderBak.regChannelId
     *
     * @mbggenerated
     */
    public void setRegChannelId(Integer regChannelId) {
        this.regChannelId = regChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGiftOrderBak.regSubChannelId
     *
     * @return the value of tbGiftOrderBak.regSubChannelId
     *
     * @mbggenerated
     */
    public Integer getRegSubChannelId() {
        return regSubChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGiftOrderBak.regSubChannelId
     *
     * @param regSubChannelId the value for tbGiftOrderBak.regSubChannelId
     *
     * @mbggenerated
     */
    public void setRegSubChannelId(Integer regSubChannelId) {
        this.regSubChannelId = regSubChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGiftOrderBak.submitChannelId
     *
     * @return the value of tbGiftOrderBak.submitChannelId
     *
     * @mbggenerated
     */
    public Integer getSubmitChannelId() {
        return submitChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGiftOrderBak.submitChannelId
     *
     * @param submitChannelId the value for tbGiftOrderBak.submitChannelId
     *
     * @mbggenerated
     */
    public void setSubmitChannelId(Integer submitChannelId) {
        this.submitChannelId = submitChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGiftOrderBak.submitSubChannelId
     *
     * @return the value of tbGiftOrderBak.submitSubChannelId
     *
     * @mbggenerated
     */
    public Integer getSubmitSubChannelId() {
        return submitSubChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGiftOrderBak.submitSubChannelId
     *
     * @param submitSubChannelId the value for tbGiftOrderBak.submitSubChannelId
     *
     * @mbggenerated
     */
    public void setSubmitSubChannelId(Integer submitSubChannelId) {
        this.submitSubChannelId = submitSubChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGiftOrderBak.awardStr
     *
     * @return the value of tbGiftOrderBak.awardStr
     *
     * @mbggenerated
     */
    public String getAwardStr() {
        return awardStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGiftOrderBak.awardStr
     *
     * @param awardStr the value for tbGiftOrderBak.awardStr
     *
     * @mbggenerated
     */
    public void setAwardStr(String awardStr) {
        this.awardStr = awardStr == null ? null : awardStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGiftOrderBak.serialNumber
     *
     * @return the value of tbGiftOrderBak.serialNumber
     *
     * @mbggenerated
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGiftOrderBak.serialNumber
     *
     * @param serialNumber the value for tbGiftOrderBak.serialNumber
     *
     * @mbggenerated
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber == null ? null : serialNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGiftOrderBak.remark
     *
     * @return the value of tbGiftOrderBak.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGiftOrderBak.remark
     *
     * @param remark the value for tbGiftOrderBak.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGiftOrderBak.clientInfoOpersys
     *
     * @return the value of tbGiftOrderBak.clientInfoOpersys
     *
     * @mbggenerated
     */
    public Integer getClientInfoOpersys() {
        return clientInfoOpersys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGiftOrderBak.clientInfoOpersys
     *
     * @param clientInfoOpersys the value for tbGiftOrderBak.clientInfoOpersys
     *
     * @mbggenerated
     */
    public void setClientInfoOpersys(Integer clientInfoOpersys) {
        this.clientInfoOpersys = clientInfoOpersys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGiftOrderBak.clientInfoIp
     *
     * @return the value of tbGiftOrderBak.clientInfoIp
     *
     * @mbggenerated
     */
    public String getClientInfoIp() {
        return clientInfoIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGiftOrderBak.clientInfoIp
     *
     * @param clientInfoIp the value for tbGiftOrderBak.clientInfoIp
     *
     * @mbggenerated
     */
    public void setClientInfoIp(String clientInfoIp) {
        this.clientInfoIp = clientInfoIp == null ? null : clientInfoIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGiftOrderBak.billId
     *
     * @return the value of tbGiftOrderBak.billId
     *
     * @mbggenerated
     */
    public Integer getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGiftOrderBak.billId
     *
     * @param billId the value for tbGiftOrderBak.billId
     *
     * @mbggenerated
     */
    public void setBillId(Integer billId) {
        this.billId = billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGiftOrderBak.clientInfoSign
     *
     * @return the value of tbGiftOrderBak.clientInfoSign
     *
     * @mbggenerated
     */
    public String getClientInfoSign() {
        return clientInfoSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGiftOrderBak.clientInfoSign
     *
     * @param clientInfoSign the value for tbGiftOrderBak.clientInfoSign
     *
     * @mbggenerated
     */
    public void setClientInfoSign(String clientInfoSign) {
        this.clientInfoSign = clientInfoSign == null ? null : clientInfoSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGiftOrderBak.clientInfoUid
     *
     * @return the value of tbGiftOrderBak.clientInfoUid
     *
     * @mbggenerated
     */
    public String getClientInfoUid() {
        return clientInfoUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGiftOrderBak.clientInfoUid
     *
     * @param clientInfoUid the value for tbGiftOrderBak.clientInfoUid
     *
     * @mbggenerated
     */
    public void setClientInfoUid(String clientInfoUid) {
        this.clientInfoUid = clientInfoUid == null ? null : clientInfoUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGiftOrderBak
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", accountId=").append(accountId);
        sb.append(", accountName=").append(accountName);
        sb.append(", playerId=").append(playerId);
        sb.append(", playerName=").append(playerName);
        sb.append(", status=").append(status);
        sb.append(", createDate=").append(createDate);
        sb.append(", modifyDate=").append(modifyDate);
        sb.append(", areaId=").append(areaId);
        sb.append(", playerLevel=").append(playerLevel);
        sb.append(", money=").append(money);
        sb.append(", chargeType=").append(chargeType);
        sb.append(", payType=").append(payType);
        sb.append(", billDefineId=").append(billDefineId);
        sb.append(", regChannelId=").append(regChannelId);
        sb.append(", regSubChannelId=").append(regSubChannelId);
        sb.append(", submitChannelId=").append(submitChannelId);
        sb.append(", submitSubChannelId=").append(submitSubChannelId);
        sb.append(", awardStr=").append(awardStr);
        sb.append(", serialNumber=").append(serialNumber);
        sb.append(", remark=").append(remark);
        sb.append(", clientInfoOpersys=").append(clientInfoOpersys);
        sb.append(", clientInfoIp=").append(clientInfoIp);
        sb.append(", billId=").append(billId);
        sb.append(", clientInfoSign=").append(clientInfoSign);
        sb.append(", clientInfoUid=").append(clientInfoUid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}