package com.pan.example.testspringbootdemo.models;

import java.io.Serializable;
import java.util.Date;

public class Tbgmsendmailextend implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGmSendMailExtend.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGmSendMailExtend.groupId
     *
     * @mbggenerated
     */
    private Long groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGmSendMailExtend.playerId
     *
     * @mbggenerated
     */
    private Long playerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGmSendMailExtend.createTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbGmSendMailExtend
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGmSendMailExtend.id
     *
     * @return the value of tbGmSendMailExtend.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGmSendMailExtend.id
     *
     * @param id the value for tbGmSendMailExtend.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGmSendMailExtend.groupId
     *
     * @return the value of tbGmSendMailExtend.groupId
     *
     * @mbggenerated
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGmSendMailExtend.groupId
     *
     * @param groupId the value for tbGmSendMailExtend.groupId
     *
     * @mbggenerated
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGmSendMailExtend.playerId
     *
     * @return the value of tbGmSendMailExtend.playerId
     *
     * @mbggenerated
     */
    public Long getPlayerId() {
        return playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGmSendMailExtend.playerId
     *
     * @param playerId the value for tbGmSendMailExtend.playerId
     *
     * @mbggenerated
     */
    public void setPlayerId(Long playerId) {
        this.playerId = playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGmSendMailExtend.createTime
     *
     * @return the value of tbGmSendMailExtend.createTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGmSendMailExtend.createTime
     *
     * @param createTime the value for tbGmSendMailExtend.createTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGmSendMailExtend
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", groupId=").append(groupId);
        sb.append(", playerId=").append(playerId);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}