package com.pan.example.testspringbootdemo.models;

import java.io.Serializable;
import java.util.Date;

public class Tbgmplayerinfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGmPlayerInfo.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGmPlayerInfo.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGmPlayerInfo.createTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGmPlayerInfo.accountId
     *
     * @mbggenerated
     */
    private Long accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGmPlayerInfo.areaId
     *
     * @mbggenerated
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGmPlayerInfo.gmUser
     *
     * @mbggenerated
     */
    private String gmUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbGmPlayerInfo.creatUser
     *
     * @mbggenerated
     */
    private String creatUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbGmPlayerInfo
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGmPlayerInfo.id
     *
     * @return the value of tbGmPlayerInfo.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGmPlayerInfo.id
     *
     * @param id the value for tbGmPlayerInfo.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGmPlayerInfo.name
     *
     * @return the value of tbGmPlayerInfo.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGmPlayerInfo.name
     *
     * @param name the value for tbGmPlayerInfo.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGmPlayerInfo.createTime
     *
     * @return the value of tbGmPlayerInfo.createTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGmPlayerInfo.createTime
     *
     * @param createTime the value for tbGmPlayerInfo.createTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGmPlayerInfo.accountId
     *
     * @return the value of tbGmPlayerInfo.accountId
     *
     * @mbggenerated
     */
    public Long getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGmPlayerInfo.accountId
     *
     * @param accountId the value for tbGmPlayerInfo.accountId
     *
     * @mbggenerated
     */
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGmPlayerInfo.areaId
     *
     * @return the value of tbGmPlayerInfo.areaId
     *
     * @mbggenerated
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGmPlayerInfo.areaId
     *
     * @param areaId the value for tbGmPlayerInfo.areaId
     *
     * @mbggenerated
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGmPlayerInfo.gmUser
     *
     * @return the value of tbGmPlayerInfo.gmUser
     *
     * @mbggenerated
     */
    public String getGmUser() {
        return gmUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGmPlayerInfo.gmUser
     *
     * @param gmUser the value for tbGmPlayerInfo.gmUser
     *
     * @mbggenerated
     */
    public void setGmUser(String gmUser) {
        this.gmUser = gmUser == null ? null : gmUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbGmPlayerInfo.creatUser
     *
     * @return the value of tbGmPlayerInfo.creatUser
     *
     * @mbggenerated
     */
    public String getCreatUser() {
        return creatUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbGmPlayerInfo.creatUser
     *
     * @param creatUser the value for tbGmPlayerInfo.creatUser
     *
     * @mbggenerated
     */
    public void setCreatUser(String creatUser) {
        this.creatUser = creatUser == null ? null : creatUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGmPlayerInfo
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", createTime=").append(createTime);
        sb.append(", accountId=").append(accountId);
        sb.append(", areaId=").append(areaId);
        sb.append(", gmUser=").append(gmUser);
        sb.append(", creatUser=").append(creatUser);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}