package com.pan.example.testspringbootdemo.models;

import java.util.ArrayList;
import java.util.List;

public class TbloginconfigExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbLoginConfig
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbLoginConfig
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbLoginConfig
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbLoginConfig
     *
     * @mbggenerated
     */
    public TbloginconfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbLoginConfig
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbLoginConfig
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbLoginConfig
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbLoginConfig
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbLoginConfig
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbLoginConfig
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbLoginConfig
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbLoginConfig
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbLoginConfig
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbLoginConfig
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbLoginConfig
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIsMainIsNull() {
            addCriterion("isMain is null");
            return (Criteria) this;
        }

        public Criteria andIsMainIsNotNull() {
            addCriterion("isMain is not null");
            return (Criteria) this;
        }

        public Criteria andIsMainEqualTo(String value) {
            addCriterion("isMain =", value, "isMain");
            return (Criteria) this;
        }

        public Criteria andIsMainNotEqualTo(String value) {
            addCriterion("isMain <>", value, "isMain");
            return (Criteria) this;
        }

        public Criteria andIsMainGreaterThan(String value) {
            addCriterion("isMain >", value, "isMain");
            return (Criteria) this;
        }

        public Criteria andIsMainGreaterThanOrEqualTo(String value) {
            addCriterion("isMain >=", value, "isMain");
            return (Criteria) this;
        }

        public Criteria andIsMainLessThan(String value) {
            addCriterion("isMain <", value, "isMain");
            return (Criteria) this;
        }

        public Criteria andIsMainLessThanOrEqualTo(String value) {
            addCriterion("isMain <=", value, "isMain");
            return (Criteria) this;
        }

        public Criteria andIsMainLike(String value) {
            addCriterion("isMain like", value, "isMain");
            return (Criteria) this;
        }

        public Criteria andIsMainNotLike(String value) {
            addCriterion("isMain not like", value, "isMain");
            return (Criteria) this;
        }

        public Criteria andIsMainIn(List<String> values) {
            addCriterion("isMain in", values, "isMain");
            return (Criteria) this;
        }

        public Criteria andIsMainNotIn(List<String> values) {
            addCriterion("isMain not in", values, "isMain");
            return (Criteria) this;
        }

        public Criteria andIsMainBetween(String value1, String value2) {
            addCriterion("isMain between", value1, value2, "isMain");
            return (Criteria) this;
        }

        public Criteria andIsMainNotBetween(String value1, String value2) {
            addCriterion("isMain not between", value1, value2, "isMain");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("`name` is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("`name` is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("`name` =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("`name` <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("`name` >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("`name` >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("`name` <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("`name` <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("`name` like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("`name` not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("`name` in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("`name` not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("`name` between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`name` not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andLoginIpIsNull() {
            addCriterion("loginIp is null");
            return (Criteria) this;
        }

        public Criteria andLoginIpIsNotNull() {
            addCriterion("loginIp is not null");
            return (Criteria) this;
        }

        public Criteria andLoginIpEqualTo(String value) {
            addCriterion("loginIp =", value, "loginIp");
            return (Criteria) this;
        }

        public Criteria andLoginIpNotEqualTo(String value) {
            addCriterion("loginIp <>", value, "loginIp");
            return (Criteria) this;
        }

        public Criteria andLoginIpGreaterThan(String value) {
            addCriterion("loginIp >", value, "loginIp");
            return (Criteria) this;
        }

        public Criteria andLoginIpGreaterThanOrEqualTo(String value) {
            addCriterion("loginIp >=", value, "loginIp");
            return (Criteria) this;
        }

        public Criteria andLoginIpLessThan(String value) {
            addCriterion("loginIp <", value, "loginIp");
            return (Criteria) this;
        }

        public Criteria andLoginIpLessThanOrEqualTo(String value) {
            addCriterion("loginIp <=", value, "loginIp");
            return (Criteria) this;
        }

        public Criteria andLoginIpLike(String value) {
            addCriterion("loginIp like", value, "loginIp");
            return (Criteria) this;
        }

        public Criteria andLoginIpNotLike(String value) {
            addCriterion("loginIp not like", value, "loginIp");
            return (Criteria) this;
        }

        public Criteria andLoginIpIn(List<String> values) {
            addCriterion("loginIp in", values, "loginIp");
            return (Criteria) this;
        }

        public Criteria andLoginIpNotIn(List<String> values) {
            addCriterion("loginIp not in", values, "loginIp");
            return (Criteria) this;
        }

        public Criteria andLoginIpBetween(String value1, String value2) {
            addCriterion("loginIp between", value1, value2, "loginIp");
            return (Criteria) this;
        }

        public Criteria andLoginIpNotBetween(String value1, String value2) {
            addCriterion("loginIp not between", value1, value2, "loginIp");
            return (Criteria) this;
        }

        public Criteria andLoginLocalIpIsNull() {
            addCriterion("loginLocalIp is null");
            return (Criteria) this;
        }

        public Criteria andLoginLocalIpIsNotNull() {
            addCriterion("loginLocalIp is not null");
            return (Criteria) this;
        }

        public Criteria andLoginLocalIpEqualTo(String value) {
            addCriterion("loginLocalIp =", value, "loginLocalIp");
            return (Criteria) this;
        }

        public Criteria andLoginLocalIpNotEqualTo(String value) {
            addCriterion("loginLocalIp <>", value, "loginLocalIp");
            return (Criteria) this;
        }

        public Criteria andLoginLocalIpGreaterThan(String value) {
            addCriterion("loginLocalIp >", value, "loginLocalIp");
            return (Criteria) this;
        }

        public Criteria andLoginLocalIpGreaterThanOrEqualTo(String value) {
            addCriterion("loginLocalIp >=", value, "loginLocalIp");
            return (Criteria) this;
        }

        public Criteria andLoginLocalIpLessThan(String value) {
            addCriterion("loginLocalIp <", value, "loginLocalIp");
            return (Criteria) this;
        }

        public Criteria andLoginLocalIpLessThanOrEqualTo(String value) {
            addCriterion("loginLocalIp <=", value, "loginLocalIp");
            return (Criteria) this;
        }

        public Criteria andLoginLocalIpLike(String value) {
            addCriterion("loginLocalIp like", value, "loginLocalIp");
            return (Criteria) this;
        }

        public Criteria andLoginLocalIpNotLike(String value) {
            addCriterion("loginLocalIp not like", value, "loginLocalIp");
            return (Criteria) this;
        }

        public Criteria andLoginLocalIpIn(List<String> values) {
            addCriterion("loginLocalIp in", values, "loginLocalIp");
            return (Criteria) this;
        }

        public Criteria andLoginLocalIpNotIn(List<String> values) {
            addCriterion("loginLocalIp not in", values, "loginLocalIp");
            return (Criteria) this;
        }

        public Criteria andLoginLocalIpBetween(String value1, String value2) {
            addCriterion("loginLocalIp between", value1, value2, "loginLocalIp");
            return (Criteria) this;
        }

        public Criteria andLoginLocalIpNotBetween(String value1, String value2) {
            addCriterion("loginLocalIp not between", value1, value2, "loginLocalIp");
            return (Criteria) this;
        }

        public Criteria andLoginDomainIsNull() {
            addCriterion("loginDomain is null");
            return (Criteria) this;
        }

        public Criteria andLoginDomainIsNotNull() {
            addCriterion("loginDomain is not null");
            return (Criteria) this;
        }

        public Criteria andLoginDomainEqualTo(String value) {
            addCriterion("loginDomain =", value, "loginDomain");
            return (Criteria) this;
        }

        public Criteria andLoginDomainNotEqualTo(String value) {
            addCriterion("loginDomain <>", value, "loginDomain");
            return (Criteria) this;
        }

        public Criteria andLoginDomainGreaterThan(String value) {
            addCriterion("loginDomain >", value, "loginDomain");
            return (Criteria) this;
        }

        public Criteria andLoginDomainGreaterThanOrEqualTo(String value) {
            addCriterion("loginDomain >=", value, "loginDomain");
            return (Criteria) this;
        }

        public Criteria andLoginDomainLessThan(String value) {
            addCriterion("loginDomain <", value, "loginDomain");
            return (Criteria) this;
        }

        public Criteria andLoginDomainLessThanOrEqualTo(String value) {
            addCriterion("loginDomain <=", value, "loginDomain");
            return (Criteria) this;
        }

        public Criteria andLoginDomainLike(String value) {
            addCriterion("loginDomain like", value, "loginDomain");
            return (Criteria) this;
        }

        public Criteria andLoginDomainNotLike(String value) {
            addCriterion("loginDomain not like", value, "loginDomain");
            return (Criteria) this;
        }

        public Criteria andLoginDomainIn(List<String> values) {
            addCriterion("loginDomain in", values, "loginDomain");
            return (Criteria) this;
        }

        public Criteria andLoginDomainNotIn(List<String> values) {
            addCriterion("loginDomain not in", values, "loginDomain");
            return (Criteria) this;
        }

        public Criteria andLoginDomainBetween(String value1, String value2) {
            addCriterion("loginDomain between", value1, value2, "loginDomain");
            return (Criteria) this;
        }

        public Criteria andLoginDomainNotBetween(String value1, String value2) {
            addCriterion("loginDomain not between", value1, value2, "loginDomain");
            return (Criteria) this;
        }

        public Criteria andLoginPortIsNull() {
            addCriterion("loginPort is null");
            return (Criteria) this;
        }

        public Criteria andLoginPortIsNotNull() {
            addCriterion("loginPort is not null");
            return (Criteria) this;
        }

        public Criteria andLoginPortEqualTo(Integer value) {
            addCriterion("loginPort =", value, "loginPort");
            return (Criteria) this;
        }

        public Criteria andLoginPortNotEqualTo(Integer value) {
            addCriterion("loginPort <>", value, "loginPort");
            return (Criteria) this;
        }

        public Criteria andLoginPortGreaterThan(Integer value) {
            addCriterion("loginPort >", value, "loginPort");
            return (Criteria) this;
        }

        public Criteria andLoginPortGreaterThanOrEqualTo(Integer value) {
            addCriterion("loginPort >=", value, "loginPort");
            return (Criteria) this;
        }

        public Criteria andLoginPortLessThan(Integer value) {
            addCriterion("loginPort <", value, "loginPort");
            return (Criteria) this;
        }

        public Criteria andLoginPortLessThanOrEqualTo(Integer value) {
            addCriterion("loginPort <=", value, "loginPort");
            return (Criteria) this;
        }

        public Criteria andLoginPortIn(List<Integer> values) {
            addCriterion("loginPort in", values, "loginPort");
            return (Criteria) this;
        }

        public Criteria andLoginPortNotIn(List<Integer> values) {
            addCriterion("loginPort not in", values, "loginPort");
            return (Criteria) this;
        }

        public Criteria andLoginPortBetween(Integer value1, Integer value2) {
            addCriterion("loginPort between", value1, value2, "loginPort");
            return (Criteria) this;
        }

        public Criteria andLoginPortNotBetween(Integer value1, Integer value2) {
            addCriterion("loginPort not between", value1, value2, "loginPort");
            return (Criteria) this;
        }

        public Criteria andLoginRmiPortIsNull() {
            addCriterion("loginRmiPort is null");
            return (Criteria) this;
        }

        public Criteria andLoginRmiPortIsNotNull() {
            addCriterion("loginRmiPort is not null");
            return (Criteria) this;
        }

        public Criteria andLoginRmiPortEqualTo(Integer value) {
            addCriterion("loginRmiPort =", value, "loginRmiPort");
            return (Criteria) this;
        }

        public Criteria andLoginRmiPortNotEqualTo(Integer value) {
            addCriterion("loginRmiPort <>", value, "loginRmiPort");
            return (Criteria) this;
        }

        public Criteria andLoginRmiPortGreaterThan(Integer value) {
            addCriterion("loginRmiPort >", value, "loginRmiPort");
            return (Criteria) this;
        }

        public Criteria andLoginRmiPortGreaterThanOrEqualTo(Integer value) {
            addCriterion("loginRmiPort >=", value, "loginRmiPort");
            return (Criteria) this;
        }

        public Criteria andLoginRmiPortLessThan(Integer value) {
            addCriterion("loginRmiPort <", value, "loginRmiPort");
            return (Criteria) this;
        }

        public Criteria andLoginRmiPortLessThanOrEqualTo(Integer value) {
            addCriterion("loginRmiPort <=", value, "loginRmiPort");
            return (Criteria) this;
        }

        public Criteria andLoginRmiPortIn(List<Integer> values) {
            addCriterion("loginRmiPort in", values, "loginRmiPort");
            return (Criteria) this;
        }

        public Criteria andLoginRmiPortNotIn(List<Integer> values) {
            addCriterion("loginRmiPort not in", values, "loginRmiPort");
            return (Criteria) this;
        }

        public Criteria andLoginRmiPortBetween(Integer value1, Integer value2) {
            addCriterion("loginRmiPort between", value1, value2, "loginRmiPort");
            return (Criteria) this;
        }

        public Criteria andLoginRmiPortNotBetween(Integer value1, Integer value2) {
            addCriterion("loginRmiPort not between", value1, value2, "loginRmiPort");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbLoginConfig
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbLoginConfig
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}