package com.pan.example.testspringbootdemo.models;

import java.io.Serializable;
import java.util.Date;

public class Tbplayergift implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbPlayerGift.giftId
     *
     * @mbggenerated
     */
    private Long giftId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbPlayerGift.giftName
     *
     * @mbggenerated
     */
    private String giftName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbPlayerGift.channelId
     *
     * @mbggenerated
     */
    private Integer channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbPlayerGift.serverId
     *
     * @mbggenerated
     */
    private Integer serverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbPlayerGift.maxPlayer
     *
     * @mbggenerated
     */
    private Integer maxPlayer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbPlayerGift.giftCount
     *
     * @mbggenerated
     */
    private Integer giftCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbPlayerGift.minLevel
     *
     * @mbggenerated
     */
    private Integer minLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbPlayerGift.accCreatTime
     *
     * @mbggenerated
     */
    private Date accCreatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbPlayerGift.startTime
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbPlayerGift.endTime
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbPlayerGift.award
     *
     * @mbggenerated
     */
    private String award;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbPlayerGift.codeType
     *
     * @mbggenerated
     */
    private Integer codeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbPlayerGift.creatUser
     *
     * @mbggenerated
     */
    private String creatUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbPlayerGift.creatTime
     *
     * @mbggenerated
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbPlayerGift.useCount
     *
     * @mbggenerated
     */
    private Integer useCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbPlayerGift
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbPlayerGift.giftId
     *
     * @return the value of tbPlayerGift.giftId
     *
     * @mbggenerated
     */
    public Long getGiftId() {
        return giftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbPlayerGift.giftId
     *
     * @param giftId the value for tbPlayerGift.giftId
     *
     * @mbggenerated
     */
    public void setGiftId(Long giftId) {
        this.giftId = giftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbPlayerGift.giftName
     *
     * @return the value of tbPlayerGift.giftName
     *
     * @mbggenerated
     */
    public String getGiftName() {
        return giftName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbPlayerGift.giftName
     *
     * @param giftName the value for tbPlayerGift.giftName
     *
     * @mbggenerated
     */
    public void setGiftName(String giftName) {
        this.giftName = giftName == null ? null : giftName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbPlayerGift.channelId
     *
     * @return the value of tbPlayerGift.channelId
     *
     * @mbggenerated
     */
    public Integer getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbPlayerGift.channelId
     *
     * @param channelId the value for tbPlayerGift.channelId
     *
     * @mbggenerated
     */
    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbPlayerGift.serverId
     *
     * @return the value of tbPlayerGift.serverId
     *
     * @mbggenerated
     */
    public Integer getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbPlayerGift.serverId
     *
     * @param serverId the value for tbPlayerGift.serverId
     *
     * @mbggenerated
     */
    public void setServerId(Integer serverId) {
        this.serverId = serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbPlayerGift.maxPlayer
     *
     * @return the value of tbPlayerGift.maxPlayer
     *
     * @mbggenerated
     */
    public Integer getMaxPlayer() {
        return maxPlayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbPlayerGift.maxPlayer
     *
     * @param maxPlayer the value for tbPlayerGift.maxPlayer
     *
     * @mbggenerated
     */
    public void setMaxPlayer(Integer maxPlayer) {
        this.maxPlayer = maxPlayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbPlayerGift.giftCount
     *
     * @return the value of tbPlayerGift.giftCount
     *
     * @mbggenerated
     */
    public Integer getGiftCount() {
        return giftCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbPlayerGift.giftCount
     *
     * @param giftCount the value for tbPlayerGift.giftCount
     *
     * @mbggenerated
     */
    public void setGiftCount(Integer giftCount) {
        this.giftCount = giftCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbPlayerGift.minLevel
     *
     * @return the value of tbPlayerGift.minLevel
     *
     * @mbggenerated
     */
    public Integer getMinLevel() {
        return minLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbPlayerGift.minLevel
     *
     * @param minLevel the value for tbPlayerGift.minLevel
     *
     * @mbggenerated
     */
    public void setMinLevel(Integer minLevel) {
        this.minLevel = minLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbPlayerGift.accCreatTime
     *
     * @return the value of tbPlayerGift.accCreatTime
     *
     * @mbggenerated
     */
    public Date getAccCreatTime() {
        return accCreatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbPlayerGift.accCreatTime
     *
     * @param accCreatTime the value for tbPlayerGift.accCreatTime
     *
     * @mbggenerated
     */
    public void setAccCreatTime(Date accCreatTime) {
        this.accCreatTime = accCreatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbPlayerGift.startTime
     *
     * @return the value of tbPlayerGift.startTime
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbPlayerGift.startTime
     *
     * @param startTime the value for tbPlayerGift.startTime
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbPlayerGift.endTime
     *
     * @return the value of tbPlayerGift.endTime
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbPlayerGift.endTime
     *
     * @param endTime the value for tbPlayerGift.endTime
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbPlayerGift.award
     *
     * @return the value of tbPlayerGift.award
     *
     * @mbggenerated
     */
    public String getAward() {
        return award;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbPlayerGift.award
     *
     * @param award the value for tbPlayerGift.award
     *
     * @mbggenerated
     */
    public void setAward(String award) {
        this.award = award == null ? null : award.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbPlayerGift.codeType
     *
     * @return the value of tbPlayerGift.codeType
     *
     * @mbggenerated
     */
    public Integer getCodeType() {
        return codeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbPlayerGift.codeType
     *
     * @param codeType the value for tbPlayerGift.codeType
     *
     * @mbggenerated
     */
    public void setCodeType(Integer codeType) {
        this.codeType = codeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbPlayerGift.creatUser
     *
     * @return the value of tbPlayerGift.creatUser
     *
     * @mbggenerated
     */
    public String getCreatUser() {
        return creatUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbPlayerGift.creatUser
     *
     * @param creatUser the value for tbPlayerGift.creatUser
     *
     * @mbggenerated
     */
    public void setCreatUser(String creatUser) {
        this.creatUser = creatUser == null ? null : creatUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbPlayerGift.creatTime
     *
     * @return the value of tbPlayerGift.creatTime
     *
     * @mbggenerated
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbPlayerGift.creatTime
     *
     * @param creatTime the value for tbPlayerGift.creatTime
     *
     * @mbggenerated
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbPlayerGift.useCount
     *
     * @return the value of tbPlayerGift.useCount
     *
     * @mbggenerated
     */
    public Integer getUseCount() {
        return useCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbPlayerGift.useCount
     *
     * @param useCount the value for tbPlayerGift.useCount
     *
     * @mbggenerated
     */
    public void setUseCount(Integer useCount) {
        this.useCount = useCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerGift
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", giftId=").append(giftId);
        sb.append(", giftName=").append(giftName);
        sb.append(", channelId=").append(channelId);
        sb.append(", serverId=").append(serverId);
        sb.append(", maxPlayer=").append(maxPlayer);
        sb.append(", giftCount=").append(giftCount);
        sb.append(", minLevel=").append(minLevel);
        sb.append(", accCreatTime=").append(accCreatTime);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", award=").append(award);
        sb.append(", codeType=").append(codeType);
        sb.append(", creatUser=").append(creatUser);
        sb.append(", creatTime=").append(creatTime);
        sb.append(", useCount=").append(useCount);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}