package com.pan.example.testspringbootdemo.models;

import java.io.Serializable;
import java.util.Date;

public class Tbplayergiftcode implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbPlayerGiftCode.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbPlayerGiftCode.giftId
     *
     * @mbggenerated
     */
    private Long giftId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbPlayerGiftCode.batchNumber
     *
     * @mbggenerated
     */
    private String batchNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbPlayerGiftCode.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbPlayerGiftCode.createTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbPlayerGiftCode.accountId
     *
     * @mbggenerated
     */
    private Long accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbPlayerGiftCode.playerId
     *
     * @mbggenerated
     */
    private Long playerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbPlayerGiftCode.channelId
     *
     * @mbggenerated
     */
    private Integer channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbPlayerGiftCode.useTime
     *
     * @mbggenerated
     */
    private Date useTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbPlayerGiftCode.serverId
     *
     * @mbggenerated
     */
    private Integer serverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbPlayerGiftCode
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbPlayerGiftCode.code
     *
     * @return the value of tbPlayerGiftCode.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbPlayerGiftCode.code
     *
     * @param code the value for tbPlayerGiftCode.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbPlayerGiftCode.giftId
     *
     * @return the value of tbPlayerGiftCode.giftId
     *
     * @mbggenerated
     */
    public Long getGiftId() {
        return giftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbPlayerGiftCode.giftId
     *
     * @param giftId the value for tbPlayerGiftCode.giftId
     *
     * @mbggenerated
     */
    public void setGiftId(Long giftId) {
        this.giftId = giftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbPlayerGiftCode.batchNumber
     *
     * @return the value of tbPlayerGiftCode.batchNumber
     *
     * @mbggenerated
     */
    public String getBatchNumber() {
        return batchNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbPlayerGiftCode.batchNumber
     *
     * @param batchNumber the value for tbPlayerGiftCode.batchNumber
     *
     * @mbggenerated
     */
    public void setBatchNumber(String batchNumber) {
        this.batchNumber = batchNumber == null ? null : batchNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbPlayerGiftCode.status
     *
     * @return the value of tbPlayerGiftCode.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbPlayerGiftCode.status
     *
     * @param status the value for tbPlayerGiftCode.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbPlayerGiftCode.createTime
     *
     * @return the value of tbPlayerGiftCode.createTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbPlayerGiftCode.createTime
     *
     * @param createTime the value for tbPlayerGiftCode.createTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbPlayerGiftCode.accountId
     *
     * @return the value of tbPlayerGiftCode.accountId
     *
     * @mbggenerated
     */
    public Long getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbPlayerGiftCode.accountId
     *
     * @param accountId the value for tbPlayerGiftCode.accountId
     *
     * @mbggenerated
     */
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbPlayerGiftCode.playerId
     *
     * @return the value of tbPlayerGiftCode.playerId
     *
     * @mbggenerated
     */
    public Long getPlayerId() {
        return playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbPlayerGiftCode.playerId
     *
     * @param playerId the value for tbPlayerGiftCode.playerId
     *
     * @mbggenerated
     */
    public void setPlayerId(Long playerId) {
        this.playerId = playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbPlayerGiftCode.channelId
     *
     * @return the value of tbPlayerGiftCode.channelId
     *
     * @mbggenerated
     */
    public Integer getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbPlayerGiftCode.channelId
     *
     * @param channelId the value for tbPlayerGiftCode.channelId
     *
     * @mbggenerated
     */
    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbPlayerGiftCode.useTime
     *
     * @return the value of tbPlayerGiftCode.useTime
     *
     * @mbggenerated
     */
    public Date getUseTime() {
        return useTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbPlayerGiftCode.useTime
     *
     * @param useTime the value for tbPlayerGiftCode.useTime
     *
     * @mbggenerated
     */
    public void setUseTime(Date useTime) {
        this.useTime = useTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbPlayerGiftCode.serverId
     *
     * @return the value of tbPlayerGiftCode.serverId
     *
     * @mbggenerated
     */
    public Integer getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbPlayerGiftCode.serverId
     *
     * @param serverId the value for tbPlayerGiftCode.serverId
     *
     * @mbggenerated
     */
    public void setServerId(Integer serverId) {
        this.serverId = serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerGiftCode
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", code=").append(code);
        sb.append(", giftId=").append(giftId);
        sb.append(", batchNumber=").append(batchNumber);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", accountId=").append(accountId);
        sb.append(", playerId=").append(playerId);
        sb.append(", channelId=").append(channelId);
        sb.append(", useTime=").append(useTime);
        sb.append(", serverId=").append(serverId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}