package com.pan.example.testspringbootdemo.dao;

import com.pan.example.testspringbootdemo.models.Tbaccount;
import com.pan.example.testspringbootdemo.models.TbaccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbaccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbAccount
     *
     * @mbggenerated
     */
    int countByExample(TbaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbAccount
     *
     * @mbggenerated
     */
    int deleteByExample(TbaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbAccount
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbAccount
     *
     * @mbggenerated
     */
    int insert(Tbaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbAccount
     *
     * @mbggenerated
     */
    int insertSelective(Tbaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbAccount
     *
     * @mbggenerated
     */
    List<Tbaccount> selectByExample(TbaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbAccount
     *
     * @mbggenerated
     */
    Tbaccount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbAccount
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Tbaccount record, @Param("example") TbaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbAccount
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Tbaccount record, @Param("example") TbaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbAccount
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tbaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbAccount
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tbaccount record);
}