package com.pan.example.testspringbootdemo.dao;

import com.pan.example.testspringbootdemo.models.Tbareaconfigbackups;
import com.pan.example.testspringbootdemo.models.TbareaconfigbackupsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbareaconfigbackupsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbAreaConfigBackups
     *
     * @mbggenerated
     */
    int countByExample(TbareaconfigbackupsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbAreaConfigBackups
     *
     * @mbggenerated
     */
    int deleteByExample(TbareaconfigbackupsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbAreaConfigBackups
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbAreaConfigBackups
     *
     * @mbggenerated
     */
    int insert(Tbareaconfigbackups record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbAreaConfigBackups
     *
     * @mbggenerated
     */
    int insertSelective(Tbareaconfigbackups record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbAreaConfigBackups
     *
     * @mbggenerated
     */
    List<Tbareaconfigbackups> selectByExample(TbareaconfigbackupsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbAreaConfigBackups
     *
     * @mbggenerated
     */
    Tbareaconfigbackups selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbAreaConfigBackups
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Tbareaconfigbackups record, @Param("example") TbareaconfigbackupsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbAreaConfigBackups
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Tbareaconfigbackups record, @Param("example") TbareaconfigbackupsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbAreaConfigBackups
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tbareaconfigbackups record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbAreaConfigBackups
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tbareaconfigbackups record);
}