package com.pan.example.testspringbootdemo.dao;

import com.pan.example.testspringbootdemo.models.Tbbillorderbak;
import com.pan.example.testspringbootdemo.models.TbbillorderbakExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbbillorderbakMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbBillOrderBak
     *
     * @mbggenerated
     */
    int countByExample(TbbillorderbakExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbBillOrderBak
     *
     * @mbggenerated
     */
    int deleteByExample(TbbillorderbakExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbBillOrderBak
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbBillOrderBak
     *
     * @mbggenerated
     */
    int insert(Tbbillorderbak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbBillOrderBak
     *
     * @mbggenerated
     */
    int insertSelective(Tbbillorderbak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbBillOrderBak
     *
     * @mbggenerated
     */
    List<Tbbillorderbak> selectByExample(TbbillorderbakExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbBillOrderBak
     *
     * @mbggenerated
     */
    Tbbillorderbak selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbBillOrderBak
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Tbbillorderbak record, @Param("example") TbbillorderbakExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbBillOrderBak
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Tbbillorderbak record, @Param("example") TbbillorderbakExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbBillOrderBak
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tbbillorderbak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbBillOrderBak
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tbbillorderbak record);
}