package com.pan.example.testspringbootdemo.dao;

import com.pan.example.testspringbootdemo.models.Tbchannelcontactinformation;
import com.pan.example.testspringbootdemo.models.TbchannelcontactinformationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbchannelcontactinformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbChannelContactInformation
     *
     * @mbggenerated
     */
    int countByExample(TbchannelcontactinformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbChannelContactInformation
     *
     * @mbggenerated
     */
    int deleteByExample(TbchannelcontactinformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbChannelContactInformation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer channel);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbChannelContactInformation
     *
     * @mbggenerated
     */
    int insert(Tbchannelcontactinformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbChannelContactInformation
     *
     * @mbggenerated
     */
    int insertSelective(Tbchannelcontactinformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbChannelContactInformation
     *
     * @mbggenerated
     */
    List<Tbchannelcontactinformation> selectByExampleWithBLOBs(TbchannelcontactinformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbChannelContactInformation
     *
     * @mbggenerated
     */
    List<Tbchannelcontactinformation> selectByExample(TbchannelcontactinformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbChannelContactInformation
     *
     * @mbggenerated
     */
    Tbchannelcontactinformation selectByPrimaryKey(Integer channel);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbChannelContactInformation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Tbchannelcontactinformation record, @Param("example") TbchannelcontactinformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbChannelContactInformation
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Tbchannelcontactinformation record, @Param("example") TbchannelcontactinformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbChannelContactInformation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Tbchannelcontactinformation record, @Param("example") TbchannelcontactinformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbChannelContactInformation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tbchannelcontactinformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbChannelContactInformation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Tbchannelcontactinformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbChannelContactInformation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tbchannelcontactinformation record);
}