package com.pan.example.testspringbootdemo.dao;

import com.pan.example.testspringbootdemo.models.Tbclient;
import com.pan.example.testspringbootdemo.models.TbclientExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbclientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbClient
     *
     * @mbggenerated
     */
    int countByExample(TbclientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbClient
     *
     * @mbggenerated
     */
    int deleteByExample(TbclientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbClient
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbClient
     *
     * @mbggenerated
     */
    int insert(Tbclient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbClient
     *
     * @mbggenerated
     */
    int insertSelective(Tbclient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbClient
     *
     * @mbggenerated
     */
    List<Tbclient> selectByExample(TbclientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbClient
     *
     * @mbggenerated
     */
    Tbclient selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbClient
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Tbclient record, @Param("example") TbclientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbClient
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Tbclient record, @Param("example") TbclientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbClient
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tbclient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbClient
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tbclient record);
}