package com.pan.example.testspringbootdemo.dao;

import com.pan.example.testspringbootdemo.models.Tbfightserverconfig;
import com.pan.example.testspringbootdemo.models.TbfightserverconfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbfightserverconfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbFightServerConfig
     *
     * @mbggenerated
     */
    int countByExample(TbfightserverconfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbFightServerConfig
     *
     * @mbggenerated
     */
    int deleteByExample(TbfightserverconfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbFightServerConfig
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbFightServerConfig
     *
     * @mbggenerated
     */
    int insert(Tbfightserverconfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbFightServerConfig
     *
     * @mbggenerated
     */
    int insertSelective(Tbfightserverconfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbFightServerConfig
     *
     * @mbggenerated
     */
    List<Tbfightserverconfig> selectByExample(TbfightserverconfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbFightServerConfig
     *
     * @mbggenerated
     */
    Tbfightserverconfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbFightServerConfig
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Tbfightserverconfig record, @Param("example") TbfightserverconfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbFightServerConfig
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Tbfightserverconfig record, @Param("example") TbfightserverconfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbFightServerConfig
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tbfightserverconfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbFightServerConfig
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tbfightserverconfig record);
}