package com.pan.example.testspringbootdemo.dao;

import com.pan.example.testspringbootdemo.models.Tbfightcheckserverconfig;
import com.pan.example.testspringbootdemo.models.TbfightcheckserverconfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbfightcheckserverconfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbFightCheckServerConfig
     *
     * @mbggenerated
     */
    int countByExample(TbfightcheckserverconfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbFightCheckServerConfig
     *
     * @mbggenerated
     */
    int deleteByExample(TbfightcheckserverconfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbFightCheckServerConfig
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbFightCheckServerConfig
     *
     * @mbggenerated
     */
    int insert(Tbfightcheckserverconfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbFightCheckServerConfig
     *
     * @mbggenerated
     */
    int insertSelective(Tbfightcheckserverconfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbFightCheckServerConfig
     *
     * @mbggenerated
     */
    List<Tbfightcheckserverconfig> selectByExample(TbfightcheckserverconfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbFightCheckServerConfig
     *
     * @mbggenerated
     */
    Tbfightcheckserverconfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbFightCheckServerConfig
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Tbfightcheckserverconfig record, @Param("example") TbfightcheckserverconfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbFightCheckServerConfig
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Tbfightcheckserverconfig record, @Param("example") TbfightcheckserverconfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbFightCheckServerConfig
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tbfightcheckserverconfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbFightCheckServerConfig
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tbfightcheckserverconfig record);
}