package com.pan.example.testspringbootdemo.dao;

import com.pan.example.testspringbootdemo.models.Tbgamenotice;
import com.pan.example.testspringbootdemo.models.TbgamenoticeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbgamenoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameNotice
     *
     * @mbggenerated
     */
    int countByExample(TbgamenoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameNotice
     *
     * @mbggenerated
     */
    int deleteByExample(TbgamenoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameNotice
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameNotice
     *
     * @mbggenerated
     */
    int insert(Tbgamenotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameNotice
     *
     * @mbggenerated
     */
    int insertSelective(Tbgamenotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameNotice
     *
     * @mbggenerated
     */
    List<Tbgamenotice> selectByExampleWithBLOBs(TbgamenoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameNotice
     *
     * @mbggenerated
     */
    List<Tbgamenotice> selectByExample(TbgamenoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameNotice
     *
     * @mbggenerated
     */
    Tbgamenotice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameNotice
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Tbgamenotice record, @Param("example") TbgamenoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameNotice
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Tbgamenotice record, @Param("example") TbgamenoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameNotice
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Tbgamenotice record, @Param("example") TbgamenoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameNotice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tbgamenotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameNotice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Tbgamenotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameNotice
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tbgamenotice record);
}