package com.pan.example.testspringbootdemo.dao;

import com.pan.example.testspringbootdemo.models.Tbgamesetting;
import com.pan.example.testspringbootdemo.models.TbgamesettingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbgamesettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameSetting
     *
     * @mbggenerated
     */
    int countByExample(TbgamesettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameSetting
     *
     * @mbggenerated
     */
    int deleteByExample(TbgamesettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameSetting
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameSetting
     *
     * @mbggenerated
     */
    int insert(Tbgamesetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameSetting
     *
     * @mbggenerated
     */
    int insertSelective(Tbgamesetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameSetting
     *
     * @mbggenerated
     */
    List<Tbgamesetting> selectByExample(TbgamesettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameSetting
     *
     * @mbggenerated
     */
    Tbgamesetting selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameSetting
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Tbgamesetting record, @Param("example") TbgamesettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameSetting
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Tbgamesetting record, @Param("example") TbgamesettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameSetting
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tbgamesetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameSetting
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tbgamesetting record);
}