package com.pan.example.testspringbootdemo.dao;

import com.pan.example.testspringbootdemo.models.Tbgamewarning;
import com.pan.example.testspringbootdemo.models.TbgamewarningExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbgamewarningMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameWarning
     *
     * @mbggenerated
     */
    int countByExample(TbgamewarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameWarning
     *
     * @mbggenerated
     */
    int deleteByExample(TbgamewarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameWarning
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameWarning
     *
     * @mbggenerated
     */
    int insert(Tbgamewarning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameWarning
     *
     * @mbggenerated
     */
    int insertSelective(Tbgamewarning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameWarning
     *
     * @mbggenerated
     */
    List<Tbgamewarning> selectByExample(TbgamewarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameWarning
     *
     * @mbggenerated
     */
    Tbgamewarning selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameWarning
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Tbgamewarning record, @Param("example") TbgamewarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameWarning
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Tbgamewarning record, @Param("example") TbgamewarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameWarning
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tbgamewarning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameWarning
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tbgamewarning record);
}