package com.pan.example.testspringbootdemo.dao;

import com.pan.example.testspringbootdemo.models.Tbgameloginaccountinfo;
import com.pan.example.testspringbootdemo.models.TbgameloginaccountinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbgameloginaccountinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameLoginAccountInfo
     *
     * @mbggenerated
     */
    int countByExample(TbgameloginaccountinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameLoginAccountInfo
     *
     * @mbggenerated
     */
    int deleteByExample(TbgameloginaccountinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameLoginAccountInfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameLoginAccountInfo
     *
     * @mbggenerated
     */
    int insert(Tbgameloginaccountinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameLoginAccountInfo
     *
     * @mbggenerated
     */
    int insertSelective(Tbgameloginaccountinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameLoginAccountInfo
     *
     * @mbggenerated
     */
    List<Tbgameloginaccountinfo> selectByExample(TbgameloginaccountinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameLoginAccountInfo
     *
     * @mbggenerated
     */
    Tbgameloginaccountinfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameLoginAccountInfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Tbgameloginaccountinfo record, @Param("example") TbgameloginaccountinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameLoginAccountInfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Tbgameloginaccountinfo record, @Param("example") TbgameloginaccountinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameLoginAccountInfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tbgameloginaccountinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGameLoginAccountInfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tbgameloginaccountinfo record);
}