package com.pan.example.testspringbootdemo.dao;

import com.pan.example.testspringbootdemo.models.Tbgiftorderbak;
import com.pan.example.testspringbootdemo.models.TbgiftorderbakExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbgiftorderbakMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGiftOrderBak
     *
     * @mbggenerated
     */
    int countByExample(TbgiftorderbakExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGiftOrderBak
     *
     * @mbggenerated
     */
    int deleteByExample(TbgiftorderbakExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGiftOrderBak
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGiftOrderBak
     *
     * @mbggenerated
     */
    int insert(Tbgiftorderbak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGiftOrderBak
     *
     * @mbggenerated
     */
    int insertSelective(Tbgiftorderbak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGiftOrderBak
     *
     * @mbggenerated
     */
    List<Tbgiftorderbak> selectByExample(TbgiftorderbakExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGiftOrderBak
     *
     * @mbggenerated
     */
    Tbgiftorderbak selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGiftOrderBak
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Tbgiftorderbak record, @Param("example") TbgiftorderbakExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGiftOrderBak
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Tbgiftorderbak record, @Param("example") TbgiftorderbakExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGiftOrderBak
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tbgiftorderbak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGiftOrderBak
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tbgiftorderbak record);
}