package com.pan.example.testspringbootdemo.dao;

import com.pan.example.testspringbootdemo.models.Tbgmsendmail;
import com.pan.example.testspringbootdemo.models.TbgmsendmailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbgmsendmailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGmSendMail
     *
     * @mbggenerated
     */
    int countByExample(TbgmsendmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGmSendMail
     *
     * @mbggenerated
     */
    int deleteByExample(TbgmsendmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGmSendMail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGmSendMail
     *
     * @mbggenerated
     */
    int insert(Tbgmsendmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGmSendMail
     *
     * @mbggenerated
     */
    int insertSelective(Tbgmsendmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGmSendMail
     *
     * @mbggenerated
     */
    List<Tbgmsendmail> selectByExampleWithBLOBs(TbgmsendmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGmSendMail
     *
     * @mbggenerated
     */
    List<Tbgmsendmail> selectByExample(TbgmsendmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGmSendMail
     *
     * @mbggenerated
     */
    Tbgmsendmail selectByPrimaryKey(Long groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGmSendMail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Tbgmsendmail record, @Param("example") TbgmsendmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGmSendMail
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Tbgmsendmail record, @Param("example") TbgmsendmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGmSendMail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Tbgmsendmail record, @Param("example") TbgmsendmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGmSendMail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tbgmsendmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGmSendMail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Tbgmsendmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGmSendMail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tbgmsendmail record);
}