package com.pan.example.testspringbootdemo.dao;

import com.pan.example.testspringbootdemo.models.Tbgmsendmailextend;
import com.pan.example.testspringbootdemo.models.TbgmsendmailextendExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbgmsendmailextendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGmSendMailExtend
     *
     * @mbggenerated
     */
    int countByExample(TbgmsendmailextendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGmSendMailExtend
     *
     * @mbggenerated
     */
    int deleteByExample(TbgmsendmailextendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGmSendMailExtend
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGmSendMailExtend
     *
     * @mbggenerated
     */
    int insert(Tbgmsendmailextend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGmSendMailExtend
     *
     * @mbggenerated
     */
    int insertSelective(Tbgmsendmailextend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGmSendMailExtend
     *
     * @mbggenerated
     */
    List<Tbgmsendmailextend> selectByExample(TbgmsendmailextendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGmSendMailExtend
     *
     * @mbggenerated
     */
    Tbgmsendmailextend selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGmSendMailExtend
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Tbgmsendmailextend record, @Param("example") TbgmsendmailextendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGmSendMailExtend
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Tbgmsendmailextend record, @Param("example") TbgmsendmailextendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGmSendMailExtend
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tbgmsendmailextend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbGmSendMailExtend
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tbgmsendmailextend record);
}