package com.pan.example.testspringbootdemo.dao;

import com.pan.example.testspringbootdemo.models.Tbloginconfig;
import com.pan.example.testspringbootdemo.models.TbloginconfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbloginconfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbLoginConfig
     *
     * @mbggenerated
     */
    int countByExample(TbloginconfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbLoginConfig
     *
     * @mbggenerated
     */
    int deleteByExample(TbloginconfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbLoginConfig
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbLoginConfig
     *
     * @mbggenerated
     */
    int insert(Tbloginconfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbLoginConfig
     *
     * @mbggenerated
     */
    int insertSelective(Tbloginconfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbLoginConfig
     *
     * @mbggenerated
     */
    List<Tbloginconfig> selectByExample(TbloginconfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbLoginConfig
     *
     * @mbggenerated
     */
    Tbloginconfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbLoginConfig
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Tbloginconfig record, @Param("example") TbloginconfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbLoginConfig
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Tbloginconfig record, @Param("example") TbloginconfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbLoginConfig
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tbloginconfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbLoginConfig
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tbloginconfig record);
}