package com.pan.example.testspringbootdemo.dao;

import com.pan.example.testspringbootdemo.models.Tbmonthcardbak;
import com.pan.example.testspringbootdemo.models.TbmonthcardbakExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbmonthcardbakMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbMonthCardBak
     *
     * @mbggenerated
     */
    int countByExample(TbmonthcardbakExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbMonthCardBak
     *
     * @mbggenerated
     */
    int deleteByExample(TbmonthcardbakExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbMonthCardBak
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long playerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbMonthCardBak
     *
     * @mbggenerated
     */
    int insert(Tbmonthcardbak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbMonthCardBak
     *
     * @mbggenerated
     */
    int insertSelective(Tbmonthcardbak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbMonthCardBak
     *
     * @mbggenerated
     */
    List<Tbmonthcardbak> selectByExample(TbmonthcardbakExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbMonthCardBak
     *
     * @mbggenerated
     */
    Tbmonthcardbak selectByPrimaryKey(Long playerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbMonthCardBak
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Tbmonthcardbak record, @Param("example") TbmonthcardbakExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbMonthCardBak
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Tbmonthcardbak record, @Param("example") TbmonthcardbakExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbMonthCardBak
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tbmonthcardbak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbMonthCardBak
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tbmonthcardbak record);
}