package com.pan.example.testspringbootdemo.dao;

import com.pan.example.testspringbootdemo.models.Tbplayergift;
import com.pan.example.testspringbootdemo.models.TbplayergiftExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbplayergiftMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerGift
     *
     * @mbggenerated
     */
    int countByExample(TbplayergiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerGift
     *
     * @mbggenerated
     */
    int deleteByExample(TbplayergiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerGift
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long giftId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerGift
     *
     * @mbggenerated
     */
    int insert(Tbplayergift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerGift
     *
     * @mbggenerated
     */
    int insertSelective(Tbplayergift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerGift
     *
     * @mbggenerated
     */
    List<Tbplayergift> selectByExample(TbplayergiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerGift
     *
     * @mbggenerated
     */
    Tbplayergift selectByPrimaryKey(Long giftId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerGift
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Tbplayergift record, @Param("example") TbplayergiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerGift
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Tbplayergift record, @Param("example") TbplayergiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerGift
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tbplayergift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerGift
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tbplayergift record);
}