package com.pan.example.testspringbootdemo.dao;

import com.pan.example.testspringbootdemo.models.Tbplayergiftcode;
import com.pan.example.testspringbootdemo.models.TbplayergiftcodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbplayergiftcodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerGiftCode
     *
     * @mbggenerated
     */
    int countByExample(TbplayergiftcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerGiftCode
     *
     * @mbggenerated
     */
    int deleteByExample(TbplayergiftcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerGiftCode
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerGiftCode
     *
     * @mbggenerated
     */
    int insert(Tbplayergiftcode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerGiftCode
     *
     * @mbggenerated
     */
    int insertSelective(Tbplayergiftcode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerGiftCode
     *
     * @mbggenerated
     */
    List<Tbplayergiftcode> selectByExample(TbplayergiftcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerGiftCode
     *
     * @mbggenerated
     */
    Tbplayergiftcode selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerGiftCode
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Tbplayergiftcode record, @Param("example") TbplayergiftcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerGiftCode
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Tbplayergiftcode record, @Param("example") TbplayergiftcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerGiftCode
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tbplayergiftcode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerGiftCode
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tbplayergiftcode record);
}