package com.pan.example.testspringbootdemo.dao;

import com.pan.example.testspringbootdemo.models.Tbplayerinfo;
import com.pan.example.testspringbootdemo.models.TbplayerinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbplayerinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerInfo
     *
     * @mbggenerated
     */
    int countByExample(TbplayerinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerInfo
     *
     * @mbggenerated
     */
    int deleteByExample(TbplayerinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerInfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerInfo
     *
     * @mbggenerated
     */
    int insert(Tbplayerinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerInfo
     *
     * @mbggenerated
     */
    int insertSelective(Tbplayerinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerInfo
     *
     * @mbggenerated
     */
    List<Tbplayerinfo> selectByExample(TbplayerinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerInfo
     *
     * @mbggenerated
     */
    Tbplayerinfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerInfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Tbplayerinfo record, @Param("example") TbplayerinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerInfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Tbplayerinfo record, @Param("example") TbplayerinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerInfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tbplayerinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbPlayerInfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tbplayerinfo record);
}