package com.pan.example.testspringbootdemo.dao;

import com.pan.example.testspringbootdemo.models.Tbrewarditems;
import com.pan.example.testspringbootdemo.models.TbrewarditemsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbrewarditemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbRewardItems
     *
     * @mbggenerated
     */
    int countByExample(TbrewarditemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbRewardItems
     *
     * @mbggenerated
     */
    int deleteByExample(TbrewarditemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbRewardItems
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbRewardItems
     *
     * @mbggenerated
     */
    int insert(Tbrewarditems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbRewardItems
     *
     * @mbggenerated
     */
    int insertSelective(Tbrewarditems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbRewardItems
     *
     * @mbggenerated
     */
    List<Tbrewarditems> selectByExample(TbrewarditemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbRewardItems
     *
     * @mbggenerated
     */
    Tbrewarditems selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbRewardItems
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Tbrewarditems record, @Param("example") TbrewarditemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbRewardItems
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Tbrewarditems record, @Param("example") TbrewarditemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbRewardItems
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tbrewarditems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbRewardItems
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tbrewarditems record);
}